name: Run MATLAB
on:
  workflow_dispatch: {}
  push: {}
jobs:
  my-job:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Curve_Fitting_Toolbox Optimization_Toolbox
          release: R2025a
          cache: true
      - name: Run command
        uses: matlab-actions/run-command@v2
        with:
          command: disp('hello world')
